'use client';
import {useEffect,useRef,useState} from "react";
import {createUserWithEmailAndPassword,sendEmailVerification,signInWithEmailAndPassword,onAuthStateChanged,signOut} from "firebase/auth";
import {doc,getDoc,setDoc,collection,addDoc,getDocs,query,orderBy,limit,serverTimestamp} from "firebase/firestore";
import {auth,db} from "../lib/firebase";
import {getPoseLandmarker,angle,avg} from "../lib/pose";

const WS={Iniciante:[["Corpo inteiro","20 min","Leve",["Agachamento 3×10","Flexão adaptada 3×8","Abdominal 3×12","Prancha 3×20s"]],["Perda de peso","25 min","Leve",["Agachamento 3×12","Marcha 3×60s","Abdominal 3×12","Prancha 3×20s"]],["Condicionamento","15 min","Leve",["Agachamento 3×10","Polichinelo 3×30s","Prancha 3×20s"]]],Intermediário:[["Corpo inteiro","30 min","Moderado",["Agachamento 4×12","Flexão 4×10","Abdominal 4×15","Prancha 3×40s"]],["Força e definição","35 min","Moderado",["Agachamento 4×15","Flexão 4×10","Afundo 3×10","Prancha 3×45s"]],["Cardio + força","30 min","Moderado",["Agachamento 4×12","Corrida parada 4×45s","Flexão 3×10"]]],Avançado:[["Alta intensidade","40 min","Intenso",["Agachamento 5×15","Burpee 4×10","Flexão 4×15","Prancha 3×60s"]],["Força avançada","45 min","Intenso",["Agachamento 5×20","Flexão 5×15","Afundo 4×12","Prancha 4×60s"]],["Full body avançado","50 min","Intenso",["Agachamento 5×20","Burpee 5×12","Flexão 5×15","Abdominal 5×20"]]]};
const DEF={name:"",age:"",height:"",weight:"",goal:"Perda de peso",days:3,level:"Iniciante",waterGoal:2500};

export default function Home(){
 const[user,setUser]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[mode,setMode]=useState("login"),[form,setForm]=useState({email:"",password:"",name:""}),[error,setError]=useState(""),[screen,setScreen]=useState("home");
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(!u){setProfile(null);setLoading(false);return}try{const s=await getDoc(doc(db,"usuarios",u.uid));setProfile(s.exists()?s.data():DEF)}finally{setLoading(false)}}),[]);
 async function submit(e){e.preventDefault();setError("");try{if(mode==="register"){const c=await createUserWithEmailAndPassword(auth,form.email.trim(),form.password);await sendEmailVerification(c.user);const p={...DEF,name:form.name.trim(),createdAt:serverTimestamp()};await setDoc(doc(db,"usuarios",c.user.uid),p);setProfile(p)}else await signInWithEmailAndPassword(auth,form.email.trim(),form.password)}catch(e){setError({"auth/invalid-credential":"E-mail ou senha incorretos.","auth/email-already-in-use":"Este e-mail já está cadastrado.","auth/weak-password":"Use uma senha mais forte."}[e.code]||"Não foi possível concluir.")}}
 async function save(p){await setDoc(doc(db,"usuarios",user.uid),{...p,updatedAt:serverTimestamp()},{merge:true});setProfile(x=>({...x,...p}))}
 if(loading)return <div className="splash"><b>W</b><strong>WKORA</strong><small>FITNESS</small></div>;
 if(!user)return <Auth mode={mode} setMode={setMode} form={form} setForm={setForm} submit={submit} error={error}/>;
 if(!profile?.name||!profile?.height||!profile?.weight)return <Onboard profile={profile||DEF} save={save}/>;
 return <Shell screen={screen} setScreen={setScreen} profile={profile} logout={()=>signOut(auth)}>{screen==="home"?<Dashboard p={profile} go={setScreen}/>:screen==="treinos"?<Treinos p={profile}/>:screen==="avaliacao"?<Evaluation user={user}/>:screen==="evolucao"?<Evolution user={user}/>:<Profile p={profile} save={save}/>}</Shell>
}

function Auth({mode,setMode,form,setForm,submit,error}){return <main className="auth"><div className="authCard"><div className="logo">W <b>KORA</b></div><span className="eyebrow">FITNESS</span><h1>{mode==="login"?"Volte para sua evolução.":"Comece sua evolução."}</h1><p>Treinos, hábitos e acompanhamento em um só lugar.</p><form onSubmit={submit}>{mode==="register"&&<input required placeholder="Seu nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="8" type="password" placeholder="Senha (mínimo 8 caracteres)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button className="primary">{mode==="login"?"Entrar":"Criar conta"}</button></form><button className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Criar uma conta":"Já tenho uma conta"}</button><small className="privacy">A câmera só é ativada quando você inicia uma avaliação.</small></div></main>}

function Onboard({profile,save}){const[d,setD]=useState(profile),[busy,setBusy]=useState(false);async function go(e){e.preventDefault();setBusy(true);try{await save({...d,age:Number(d.age||0),height:Number(d.height),weight:Number(d.weight),days:Number(d.days),waterGoal:Number(d.waterGoal)})}finally{setBusy(false)}}return <main className="onboard"><form className="card onboardCard" onSubmit={go}><span className="eyebrow">PERSONALIZAÇÃO</span><h1>Vamos conhecer sua rotina.</h1><div className="formGrid">{[["name","Nome","text"],["age","Idade","number"],["height","Altura (cm)","number"],["weight","Peso (kg)","number"]].map(([k,l,t])=><label key={k}>{l}<input required={k!=="age"} type={t} value={d[k]} onChange={e=>setD({...d,[k]:e.target.value})}/></label>)}<label>Objetivo<select value={d.goal} onChange={e=>setD({...d,goal:e.target.value})}>{["Perda de peso","Definição","Condicionamento","Força","Mobilidade"].map(x=><option key={x}>{x}</option>)}</select></label><label>Nível<select value={d.level} onChange={e=>setD({...d,level:e.target.value})}>{["Iniciante","Intermediário","Avançado"].map(x=><option key={x}>{x}</option>)}</select></label><label>Dias/semana<select value={d.days} onChange={e=>setD({...d,days:e.target.value})}>{[2,3,4,5,6,7].map(x=><option key={x}>{x}</option>)}</select></label><label>Meta água (ml)<input type="number" min="500" max="6000" value={d.waterGoal} onChange={e=>setD({...d,waterGoal:e.target.value})}/></label></div><button className="primary">{busy?"Salvando...":"Entrar no WKORA"}</button></form></main>}

function Shell({children,screen,setScreen,p,logout}){return <main className="app"><aside><div className="brand"><span>W</span>KORA</div><small>FITNESS</small>{[["home","⌂","Início"],["treinos","♧","Treinos"],["avaliacao","◉","Avaliação"],["evolucao","↗","Evolução"]].map(([id,i,l])=><button className={screen===id?"nav active":"nav"} onClick={()=>setScreen(id)} key={id}><b>{i}</b>{l}</button>)}<button className="profileNav" onClick={()=>setScreen("perfil")}><span>{p.name[0].toUpperCase()}</span>{p.name}</button><button className="logout" onClick={logout}>Sair</button></aside><section className="main"><header><div><span className="eyebrow">WKORA FITNESS</span><h1>{screen==="home"?"Seu dia começa aqui.":screen==="treinos"?"Escolha seu treino.":screen==="avaliacao"?"Avaliação corporal.":screen==="evolucao"?"Sua evolução.":"Meu perfil."}</h1></div><div className="avatar">{p.name[0].toUpperCase()}</div></header>{children}</section></main>}

function Dashboard({p,go}){return <div className="grid"><section className="card hero wide"><div><span className="tag">OBJETIVO ATUAL</span><h2>{p.goal}</h2><p>{p.days} dias por semana · nível {p.level}</p><button className="primary" onClick={()=>go("treinos")}>Começar treino</button></div><div className="ring">0%<small>semana</small></div></section><div className="stats wide"><Metric i="🏋️" t="Treino" v="0 / 1" s="Hoje"/><Metric i="💧" t="Água" v="0 ml" s={"Meta "+p.waterGoal+" ml"}/><Metric i="❤️" t="Cardio" v="0 min" s="Hoje"/><Metric i="🥗" t="Hábitos" v="0 / 5" s="Hoje"/></div><section className="card wide"><div className="sectionHead"><div><span className="eyebrow">WKORA VISION</span><h3>Avalie seu movimento</h3></div><button className="ghost" onClick={()=>go("avaliacao")}>Abrir avaliação</button></div><p>Use a câmera para análise guiada. O processamento corporal acontece no dispositivo e o servidor recebe somente métricas.</p></section><section className="card"><span className="eyebrow">TREINO</span><h3>Biblioteca completa</h3><p>Iniciante, intermediário e avançado.</p><button className="ghost full" onClick={()=>go("treinos")}>Ver treinos</button></section><section className="card"><span className="eyebrow">EVOLUÇÃO</span><h3>Acompanhe sua jornada</h3><p>Histórico de avaliações e desempenho.</p><button className="ghost full" onClick={()=>go("evolucao")}>Ver evolução</button></section></div>}
function Metric({i,t,v,s}){return <div className="card metric"><span>{i}</span><div><small>{t}</small><strong>{v}</strong><em>{s}</em></div></div>}

function Treinos({p}){const[l,setL]=useState(p.level),[sel,setSel]=useState(null);return <div className="stack"><div className="levels">{Object.keys(WS).map(x=><button className={l===x?"level selected":"level"} onClick={()=>setL(x)} key={x}>{x}</button>)}</div>{!sel?<div className="workouts">{WS[l].map(w=><article className="card" key={w[0]}><span className="tag">{w[2]}</span><h3>{w[0]}</h3><p>{w[1]} · treino guiado</p><ul>{w[3].map(e=><li key={e}>{e}</li>)}</ul><button className="primary full" onClick={()=>setSel(w)}>Abrir treino</button></article>)}</div>:<section className="card detail"><button className="ghost" onClick={()=>setSel(null)}>← Voltar</button><span className="tag">{sel[2]}</span><h2>{sel[0]}</h2><p>{sel[1]}</p>{sel[3].map((e,i)=><div className="exercise" key={e}><b>{String(i+1).padStart(2,"0")}</b><span>{e}</span></div>)}<button className="primary">Iniciar treino guiado</button></section>}</div>}

function Evaluation({user}){const video=useRef(),canvas=useRef(),stream=useRef(),pose=useRef(),raf=useRef(),state=useRef({phase:"up",reps:0,sum:0,n:0});const[run,setRun]=useState(false),[status,setStatus]=useState("Pronto"),[reps,setReps]=useState(0),[quality,setQuality]=useState("—"),[feed,setFeed]=useState("Ative a câmera e deixe o corpo inteiro visível."),[saving,setSaving]=useState(false);
 async function start(){try{if(!navigator.mediaDevices?.getUserMedia)throw Error();stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});video.current.srcObject=stream.current;await video.current.play();pose.current=await getPoseLandmarker();state.current={phase:"up",reps:0,sum:0,n:0};setRun(true);setStatus("Analisando");raf.current=requestAnimationFrame(loop)}catch{setStatus("Câmera indisponível");setFeed("Permita a câmera. O vídeo não é enviado ao servidor.")}}
 function loop(ts){if(!video.current||!pose.current){raf.current=requestAnimationFrame(loop);return}const r=pose.current.detectForVideo(video.current,ts);draw(r);analyze(r);raf.current=requestAnimationFrame(loop)}
 function draw(r){const c=canvas.current,v=video.current,l=r.landmarks?.[0];if(!c||!v||!l)return;const w=v.videoWidth||1280,h=v.videoHeight||720;c.width=w;c.height=h;const x=c.getContext("2d");x.clearRect(0,0,w,h);x.fillStyle="#d4b55f";x.strokeStyle="#d4b55f";x.lineWidth=3;for(const p of l)if(p.visibility>.45){x.beginPath();x.arc(p.x*w,p.y*h,5,0,7);x.fill()}[[11,13],[13,15],[12,14],[14,16],[11,12],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]].forEach(([a,b])=>{let p=l[a],q=l[b];if(p?.visibility>.45&&q?.visibility>.45){x.beginPath();x.moveTo(p.x*w,p.y*h);x.lineTo(q.x*w,q.y*h);x.stroke()}})}
 function analyze(r){const l=r.landmarks?.[0];if(!l){setFeed("Não encontrei seu corpo. Afaste o celular.");return}const ids=[11,12,23,24,25,26,27,28];if(ids.some(i=>!l[i]||l[i].visibility<.45)){setFeed("Mostre ombros, quadris, joelhos e pés.");return}const k=avg(angle(l[23],l[25],l[27]),angle(l[24],l[26],l[28])),torso=angle(l[11],l[23],l[25]);if(k==null)return;const s=state.current;s.n++;let q=100;if(torso<145)q-=20;if(k>165)s.phase="up";if(k<105&&s.phase==="up"){s.phase="down";setFeed("Boa profundidade. Suba com controle.")}if(k>160&&s.phase==="down"){s.phase="up";s.reps++;setReps(s.reps);setFeed("Repetição registrada.")}if(torso<130)setFeed("Tente manter o tronco mais alinhado.");s.sum+=Math.max(0,q);if(s.n%10===0)setQuality(Math.round(s.sum/s.n)+"%")}
 function stop(){cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setRun(false);setStatus("Encerrada")}
 async function save(){setSaving(true);try{await addDoc(collection(db,"usuarios",user.uid,"avaliacoes"),{exercise:"Agachamento",reps,quality:quality==="—"?null:Number(String(quality).replace("%","")),feedback:feed,processedLocally:true,videoStored:false,createdAt:serverTimestamp()})}finally{setSaving(false)}}useEffect(()=>()=>stop(),[]);
 return <div className="evalGrid"><section className="card cameraCard"><div className="camera"><video ref={video} playsInline muted/><canvas ref={canvas}/>{!run&&<div className="overlay"><b>WKORA VISION</b><span>O processamento é local.</span></div>}<label>{status}</label></div><div className="controls"><span>Agachamento</span>{!run?<button className="primary" onClick={start}>Ativar câmera</button>:<button className="danger" onClick={stop}>Encerrar</button>}</div></section><aside className="card eval"><span className="eyebrow">AO VIVO</span><div className="big">{reps}<small>repetições</small></div><div className="feedback"><small>FEEDBACK</small><strong>{feed}</strong></div><div className="twocol"><div>Qualidade<strong>{quality}</strong></div><div>Vídeo<strong>Local</strong></div></div><button className="primary full" disabled={!reps||saving} onClick={save}>{saving?"Salvando...":"Salvar métricas"}</button><div className="notice">🔒 Nenhum vídeo é salvo. Apenas métricas.</div><p className="disclaimer">Informativo; não é diagnóstico médico.</p></aside></div>}

function Evolution({user}){const[data,setData]=useState([]);useEffect(()=>{(async()=>{try{const q=query(collection(db,"usuarios",user.uid,"avaliacoes"),orderBy("createdAt","desc"),limit(20)),s=await getDocs(q);setData(s.docs.map(x=>({id:x.id,...x.data()})))}catch{}})()},[user.uid]);return <div className="grid"><section className="card wide"><span className="eyebrow">HISTÓRICO</span><h2>Suas avaliações</h2><p>Vídeos não entram no histórico.</p>{data.length?<div className="history">{data.map(x=><div key={x.id}><strong>{x.exercise}</strong><b>{x.reps} reps</b><span>{x.quality?x.quality+"%":"—"}</span></div>)}</div>:<div className="empty">Faça sua primeira avaliação.</div>}</section><Metric i="📷" t="Avaliações" v={data.length} s="Registradas"/><Metric i="🔥" t="Sequência" v="0 dias" s="Comece hoje"/></div>}
function Profile({p,save}){const[d,setD]=useState(p);return <form className="card profile" onSubmit={async e=>{e.preventDefault();await save({...d,height:Number(d.height),weight:Number(d.weight),days:Number(d.days),waterGoal:Number(d.waterGoal)})}}><span className="eyebrow">MEU PERFIL</span><h2>{p.name}</h2><div className="formGrid"><label>Nome<input value={d.name} onChange={e=>setD({...d,name:e.target.value})}/></label><label>Idade<input value={d.age} onChange={e=>setD({...d,age:e.target.value})}/></label><label>Altura<input value={d.height} onChange={e=>setD({...d,height:e.target.value})}/></label><label>Peso<input value={d.weight} onChange={e=>setD({...d,weight:e.target.value})}/></label><label>Objetivo<select value={d.goal} onChange={e=>setD({...d,goal:e.target.value})}>{["Perda de peso","Definição","Condicionamento","Força","Mobilidade"].map(x=><option key={x}>{x}</option>)}</select></label><label>Dias/semana<input value={d.days} onChange={e=>setD({...d,days:e.target.value})}/></label></div><button className="primary">Salvar</button></form>}
